baseurl: ""
url: "https://eurosys-aegis.github.io"
css: "/assets/hotweb.css"

markdown: kramdown
timezone: Europe/London

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - preview
google_analytics: ""
